-- One-off: export the live public schema as DDL, to seed the Supabase CLI
-- baseline migration without Docker/pg_dump. Read-only (catalog metadata
-- only). Callable only by the service role.
-- After the baseline is generated, drop it:
--   drop function if exists aistrix_schema_ddl();

create or replace function aistrix_schema_ddl()
returns text
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  out    text := '';
  r      record;
  cols   text;
  ddl    text;
begin
  out := out || format(E'-- Baseline exported %s from %s\n', now()::timestamptz(0), split_part(version(), ',', 1));
  out := out || E'set check_function_bodies = off;\nset client_min_messages = warning;\n\n';

  -- ── Extensions (already present on Supabase; no-ops there) ───────────────
  out := out || E'-- Extensions\n';
  for r in
    select e.extname, n.nspname from pg_extension e join pg_namespace n on n.oid = e.extnamespace
     where e.extname <> 'plpgsql' order by e.extname
  loop
    out := out || format(E'create extension if not exists %I with schema %I;\n', r.extname, r.nspname);
  end loop;

  -- ── Enum types ───────────────────────────────────────────────────────────
  for r in
    select t.typname, string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) as labels
      from pg_type t join pg_enum e on e.enumtypid = t.oid
     where t.typnamespace = 'public'::regnamespace group by t.typname order by t.typname
  loop
    out := out || format(E'create type public.%I as enum (%s);\n', r.typname, r.labels);
  end loop;

  -- ── Tables (columns + primary/unique/check constraints) ─────────────────
  out := out || E'\n-- Tables\n';
  for r in
    select c.oid, c.relname from pg_class c
     where c.relnamespace = 'public'::regnamespace and c.relkind = 'r'
       and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'e')
     order by c.relname
  loop
    select string_agg(
             format('  %I %s', a.attname, format_type(a.atttypid, a.atttypmod))
             || case
                  when a.attidentity = 'a' then ' generated always as identity'
                  when a.attidentity = 'd' then ' generated by default as identity'
                  when a.attgenerated = 's' then format(' generated always as (%s) stored', pg_get_expr(ad.adbin, ad.adrelid))
                  when ad.adbin is not null then ' default ' || pg_get_expr(ad.adbin, ad.adrelid)
                  else '' end
             || case when a.attnotnull then ' not null' else '' end,
             E',\n' order by a.attnum)
      into cols
      from pg_attribute a
      left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
     where a.attrelid = r.oid and a.attnum > 0 and not a.attisdropped;

    select coalesce(string_agg(format(E',\n  constraint %I %s', co.conname, pg_get_constraintdef(co.oid)),
                               '' order by co.contype desc, co.conname), '')
      into ddl
      from pg_constraint co where co.conrelid = r.oid and co.contype in ('p', 'u', 'c');

    out := out || format(E'create table public.%I (\n%s%s\n);\n', r.relname, cols, ddl);
  end loop;

  -- ── Foreign keys (after all tables exist) ────────────────────────────────
  out := out || E'\n-- Foreign keys\n';
  for r in
    select conrelid::regclass::text as tbl, conname, pg_get_constraintdef(oid) as def
      from pg_constraint where contype = 'f' and connamespace = 'public'::regnamespace
     order by 1, 2
  loop
    out := out || format(E'alter table %s add constraint %I %s;\n', r.tbl, r.conname, r.def);
  end loop;

  -- ── Indexes not backing a constraint ─────────────────────────────────────
  out := out || E'\n-- Indexes\n';
  for r in
    select i.indexrelid::regclass::text as name, pg_get_indexdef(i.indexrelid) as def
      from pg_index i join pg_class c on c.oid = i.indrelid
     where c.relnamespace = 'public'::regnamespace
       and not exists (select 1 from pg_constraint co where co.conindid = i.indexrelid)
     order by 1
  loop
    out := out || r.def || E';\n';
  end loop;

  -- ── Views ────────────────────────────────────────────────────────────────
  for r in
    select c.relname, pg_get_viewdef(c.oid, true) as def from pg_class c
     where c.relnamespace = 'public'::regnamespace and c.relkind = 'v' order by c.relname
  loop
    out := out || format(E'create or replace view public.%I as\n%s\n', r.relname, r.def);
  end loop;

  -- ── Functions ────────────────────────────────────────────────────────────
  out := out || E'\n-- Functions\n';
  for r in
    select p.oid, p.proname from pg_proc p
     where p.pronamespace = 'public'::regnamespace and p.prokind in ('f', 'p')
       and p.proname not in ('aistrix_schema_ddl', 'aistrix_schema_report')
       and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
     order by p.proname, p.oid
  loop
    out := out || pg_get_functiondef(r.oid) || E';\n\n';
  end loop;

  -- ── Function execute permissions ─────────────────────────────────────────
  out := out || E'-- Function permissions\n';
  for r in
    select p.oid::regprocedure::text as sig, p.proacl from pg_proc p
     where p.pronamespace = 'public'::regnamespace and p.prokind in ('f', 'p') and p.proacl is not null
       and p.proname not in ('aistrix_schema_ddl', 'aistrix_schema_report')
       and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
     order by 1
  loop
    out := out || format(E'revoke all on function public.%s from public, anon, authenticated;\n', r.sig);
    out := out || coalesce((
      select string_agg(format(E'grant execute on function public.%s to %s;\n', r.sig,
                               case when x.grantee = 0 then 'public' else quote_ident(x.grantee::regrole::text) end), '')
        from aclexplode(r.proacl) x
       where x.privilege_type = 'EXECUTE' and x.grantee::regrole::text not in ('postgres', 'supabase_admin')), '');
  end loop;

  -- ── Triggers (public tables + our trigger on auth.users) ─────────────────
  out := out || E'\n-- Triggers\n';
  for r in
    select pg_get_triggerdef(t.oid) as def from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_proc p on p.oid = t.tgfoid
     where not t.tgisinternal
       and (c.relnamespace = 'public'::regnamespace
            or (c.oid = 'auth.users'::regclass and p.pronamespace = 'public'::regnamespace))
     order by c.relname, t.tgname
  loop
    out := out || r.def || E';\n';
  end loop;

  -- ── Row level security + policies ────────────────────────────────────────
  out := out || E'\n-- Row level security\n';
  for r in
    select relname from pg_class where relnamespace = 'public'::regnamespace and relkind = 'r' and relrowsecurity
     order by relname
  loop
    out := out || format(E'alter table public.%I enable row level security;\n', r.relname);
  end loop;
  for r in
    select schemaname, tablename, policyname, permissive, roles, cmd, qual, with_check from pg_policies
     where schemaname = 'public'
        or (schemaname = 'storage' and tablename = 'objects' and policyname like 'aistrix\_%')
     order by schemaname, tablename, policyname
  loop
    out := out || format(E'create policy %I on %I.%I as %s for %s to %s%s%s;\n',
      r.policyname, r.schemaname, r.tablename, lower(r.permissive), lower(r.cmd),
      (select string_agg(case when x = 'public' then 'public' else quote_ident(x) end, ', ') from unnest(r.roles) x),
      case when r.qual is not null then E'\n  using (' || r.qual || ')' else '' end,
      case when r.with_check is not null then E'\n  with check (' || r.with_check || ')' else '' end);
  end loop;

  -- ── Storage buckets ──────────────────────────────────────────────────────
  out := out || E'\n-- Storage buckets\n';
  for r in
    select id, name, public, file_size_limit, allowed_mime_types from storage.buckets order by id
  loop
    out := out || format(E'insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)\nvalues (%L, %L, %s, %s, %s)\non conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;\n',
      r.id, r.name, r.public, coalesce(r.file_size_limit::text, 'null'),
      coalesce(quote_literal(r.allowed_mime_types::text) || '::text[]', 'null'));
  end loop;

  return out;
end $$;

revoke all on function aistrix_schema_ddl() from public, anon, authenticated;
grant execute on function aistrix_schema_ddl() to service_role;
